# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='package',
            field=models.CharField(choices=[('standart', 'Standart'), ('gold', 'Gold'), ('vip', 'Vip')], max_length=15),
        ),
    ]
