# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('date_receipt', models.DateField(null=True)),
                ('type_form', models.TextField(default='1-object')),
            ],
        ),
    ]
