# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shop_list',
            name='date_receipt',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='shop_cart',
            name='number_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Shop_List'),
        ),
    ]
