# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0002_auto_20161121_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cart',
            name='state_product',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='shop_cart',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
