# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20161123_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='state_product',
            field=models.TextField(max_length=10),
        ),
    ]
