# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20161123_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_cart',
            name='state_product',
        ),
    ]
