# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_shop_cart_state_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cart',
            name='state_product',
            field=models.TextField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
