# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20161123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='quantity_product',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
