# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20161123_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='state_product',
            field=models.TextField(default='add'),
        ),
    ]
