# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_auto_20161205_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
