# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20161205_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
