# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20161206_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='news',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
