# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20161206_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
